# CrowdSec security engine + firewall bouncer for eclair
# Agent detects attacks; firewall bouncer enforces bans via nftables.
# TCP-mode haproxy can't use lua/SPOE bouncer, so IP banning happens
# at the nftables layer — blocks before haproxy ever sees the connection.
#
# The bouncer API key is auto-generated by crowdsec on first boot.
# The bouncer waits for crowdsec to be fully up before starting.
{lib, ...}: {
  flake.eclairNixosModules.crowdsec = {
    pkgs,
    lib,
    ...
  }: {
    services.crowdsec = {
      enable = true;

      # Required: tells the module where to write the LAPI credentials file.
      # Without this, api.client.credentials_path is null and the unit fails to evaluate.
      settings.lapi.credentialsFile = "/var/lib/crowdsec/lapi-credentials.yaml";

      settings.general.api.server.enable = true;

      # Install collections via the hub option so the module handles it.
      hub.collections = [
        "crowdsecurity/linux"
        "crowdsecurity/haproxy"
      ];

      # Acquisitions: watch haproxy and sshd journals for attack signals.
      localConfig.acquisitions = [
        {
          source = "journalctl";
          journalctl_filter = ["-u" "haproxy.service"];
          labels.type = "haproxy";
        }
        {
          source = "journalctl";
          journalctl_filter = ["-u" "sshd.service"];
          labels.type = "syslog";
        }
      ];
    };

    # Auto-register the bouncer key before crowdsec starts.
    # Generates a stable random key, writes it to /var/lib/crowdsec/bouncer-key,
    # and registers it with the LAPI so the bouncer can authenticate.
    systemd.services.crowdsec.serviceConfig.ExecStartPre = lib.mkAfter [
      (toString (pkgs.writeShellScript "register-bouncer" ''
        set -euo pipefail
        KEY_FILE=/var/lib/crowdsec/bouncer-key
        if [ ! -f "$KEY_FILE" ]; then
          ${pkgs.openssl}/bin/openssl rand -hex 32 > "$KEY_FILE"
          chmod 600 "$KEY_FILE"
        fi
        if ! cscli bouncers list | grep -q "firewall-bouncer"; then
          cscli bouncers add firewall-bouncer --key "$(cat $KEY_FILE)"
        fi
      ''))
    ];

    # Firewall bouncer: bans IPs via nftables before they reach haproxy.
    # Inline api_key is set at runtime via an ExecStartPre script that
    # rewrites the config with the key generated by crowdsec above.
    services.crowdsec-firewall-bouncer = {
      enable = true;
      registerBouncer.enable = false;

      settings = {
        mode = "nftables";
        api_url = "http://127.0.0.1:8080/";
        # Placeholder — overwritten at runtime by the ExecStartPre below
        api_key = "placeholder";
        update_frequency = "10s";
        log_level = "info";
        deny_action = "DROP";
        deny_log = true;
      };
    };

    # Override the bouncer service to:
    # 1. Wait for crowdsec (which writes the key) to be fully running
    # 2. Patch the config file with the real key before starting
    systemd.services.crowdsec-firewall-bouncer = {
      after = ["crowdsec.service"];
      wants = ["crowdsec.service"];
      serviceConfig.ExecStartPre = lib.mkBefore [
        (toString (pkgs.writeShellScript "patch-bouncer-key" ''
          set -euo pipefail
          KEY_FILE=/var/lib/crowdsec/bouncer-key
          CONFIG_FILE=/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
          if [ -f "$KEY_FILE" ] && [ -f "$CONFIG_FILE" ]; then
            ${pkgs.gnused}/bin/sed -i \
              "s/^api_key:.*/api_key: $(cat $KEY_FILE)/" \
              "$CONFIG_FILE"
          fi
        ''))
      ];
    };

    # nftables required for the firewall bouncer
    networking.nftables.enable = true;
  };
}
