# Hardware configuration for eclair (QEMU/KVM VPS)
# Generated by nixos-generate-config, do not modify.
{
  lib,
  modulesPath,
  ...
}: {
  flake.nixosModules.eclairHardwareConfiguration = {
    lib,
    modulesPath,
    ...
  }: {
    imports = [
      (modulesPath + "/profiles/qemu-guest.nix")
    ];

    boot = {
      initrd = {
        availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk"];
        kernelModules = [];
      };
      kernelModules = [];
      extraModulePackages = [];
      loader = {
        systemd-boot.enable = true;
        efi.canTouchEfiVariables = true;
      };
    };

    fileSystems."/" = {
      device = "/dev/disk/by-uuid/2c1f0b67-d35a-407d-95cf-744b78e5295d";
      fsType = "ext4";
    };

    fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/9D6A-31FF";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };

    swapDevices = [
      {device = "/dev/disk/by-uuid/e6eb52b7-b9b5-4b5f-a0dc-00a00312b5f6";}
    ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  };
}
