name: "Deploy Configuration"
on:
  pull_request:
    types:
      - closed
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3.17.0
        with:
          extra-conf: |
            extra-experimental-features = nix-command flakes

      - name: Write SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "StrictHostKeyChecking no" > ~/.ssh/config
          echo "UserKnownHostsFile /dev/null" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Deploy
        run: nix run nixpkgs#deploy-rs -- --remote-build .#"sorbet"
        env:
          NIX_CONFIG: |
            experimental-features = nix-command flakes
